name: telehealth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  vietqr_core: 0.2.5+1
  vietqr_widget: ^0.1.1+3
  http: ^1.1.0   # 👈 Thêm http tại đây, cùng cấp với flutter, google_fonts...
  google_sign_in: ^6.1.5
  image_picker: ^1.2.0
  agora_rtc_engine: ^6.5.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
